- hosts: hello
  sudo: yes
  gather_facts: False
  tasks:
  - name: ensure hello binary is installed.
    copy: src=/opt/static/hello dest=/opt/bin/hello mode=0755

  - name: ensure hello service is installed.
    copy: src=hello{{ item }}.service dest=/etc/systemd/system/hello{{ item }}.service
          owner=root group=root mode=0644
    with_sequence: count={{ instance_count }}

  - name: ensure hello service is running.
    service: name=hello{{ item }} state=started
    with_sequence: count={{ instance_count }}
