- hosts: hello
  sudo: yes
  gather_facts: False
  tasks:
  - name: ensure hello binary is installed.
    copy: src=/opt/static/hello dest=/opt/bin/hello mode=0755

  - name: ensure hello service is installed.
    copy: src=hello.service dest=/etc/systemd/system/hello.service
          owner=root group=root mode=0644

  - name: ensure hello service is running.
    service: name=hello state=started
